version: '3.7'
services:
  db:
    container_name: for_test_db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    container_name: fastapi_app
    build: .
    command: /bin/bash -c "uvicorn src.app:app --host=0.0.0.0 --port=8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db